-- CreateEnum
CREATE TYPE "TicketState" AS ENUM ('UPLOADED', 'ITEMS_CONFIRMED', 'CONSUMERS_CONFIRMED', 'PAYERS_CONFIRMED', 'SETTLED', 'CANCELLED');

-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "state" "TicketState" NOT NULL DEFAULT 'UPLOADED';
